---
title: Burping Jelly Baby
hero_image: images/banner.png
description: Make a jelly baby burp when you squeeze it!
original_url: https://raspberrypi.org/learning/burping-jelly-baby
listed: true
ingredient: false
copyedit: true
version: 3.1
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Burping Jelly Baby
- title: Raspberry Pi GPIO pins
- title: Wiring up the jelly baby
- title: Sound of a burp!
- title: Write a program in Python
- title: What next?
